FROM node:18

RUN yarn cache clean

WORKDIR /app

COPY .yarn .yarn
COPY .yarnrc.yml .

COPY package.json yarn.lock .

COPY web/package.json ./web/

RUN yarn install

COPY . .

RUN yarn rw build web

CMD ["yarn", "rw", "serve", "web"]
