FROM node:18

RUN yarn cache clean

WORKDIR /app

COPY .yarn .yarn
COPY .yarnrc.yml .

COPY package.json yarn.lock .

COPY api/package.json ./api/

RUN yarn install

COPY . .

RUN yarn rw build api

CMD ["yarn", "rw", "serve", "api"]
