FROM node:16-alpine

RUN yarn cache clean

RUN mkdir /app
WORKDIR /app

COPY package.json .
COPY web/package.json ./web/package.json

COPY yarn.lock .
COPY .yarn .yarn
COPY .yarnrc.yml .yarnrc.yml

RUN yarn install
COPY . .

RUN yarn rw build api

CMD ["yarn", "rw", "serve", "api"]
